/* dym:SQLSource Version 1.0
---------------------------------------------------------------------
dym:TestData::
---------------------------------------------------------------------

	AuthCodes test data
	
---------------------------------------------------------------------*/

--INSERTs generated by 'sp_generate_inserts' stored procedure written by Vyas
--Build number: 22
--Problems/Suggestions? Contact Vyas @ vyaskn@hotmail.com
--http://vyaskn.tripod.com

SET IDENTITY_INSERT dbo.AuthCodes ON
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(7,'H0031','TP & ASS OPTUM')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(8,'H2019','ABA Aide direct services by paraprofessional')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(9,'G9012','BCBA Treatment- TEAM MEETING')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(16,'H0032','BCBA - Assessment / Treatment Planning')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(17,'S5110','BCBA- Direct BCBA or Parent Training')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(18,'S5108','BCBA Supervision - Value Options, AmeriGroup, NY Group Health')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(19,'H2012','BCBA- Parent Training - United/Oxford')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(20,'0368T','BCBA Assessment / Treatment Planning - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(21,'0369T','BCBA Supervision - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(22,'0360T/0361T','BCBA Post Assessment / Treatment Planning - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(23,'H2014','ABA Aide - Social Skills Group - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(24,'0370T','BCBA Parent Training - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(25,'0364T/0365T','ABA Aide - Direct Services by a paraprofessional - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(26,'0359T','BCBA - Post Assessment - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(28,'0368T/0369T','BCBA Supervision/Parent Training')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(39,'0360T','BCBA Post Assessment / Treatment Planning - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(40,'0361T','BCBA Post Assessment / Treatment Planning - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(41,'0364T','ABA Aide - Direct Services by a paraprofessional - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(42,'0365T','ABA Aide - Direct Services by a paraprofessional - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(43,'0366T','BCBA Supervision - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(44,'0367T','BCBA Supervision - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(66,'0372T','ABA - Social Skills Group - Value Options')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(69,'0362T','BCBA - Assessment/Treatment Planning - Severe Behavior')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(70,'0363T','BCBA - Assessment/Treatment Planning - Severe Behavior')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(71,'0373T','BCBA - Supervision - Severe Behavior')
INSERT INTO [AuthCodes] ([ID],[CodeCode],[CodeDescription])VALUES(72,'0374T','BCBA - Supervision - Severe Behavior')
SET IDENTITY_INSERT dbo.AuthCodes OFF